GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/products/2/ HTTP/1.1

###
DELETE http://localhost:8000/products/2/ HTTP/1.1

###
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4Mzg1NDk2LCJpYXQiOjE3MjgzODUxOTYsImp0aSI6IjVkZTNjZGYxMzExZDQ4MmU5ZjVlN2E2M2FhNzQ3Y2IxIiwidXNlcl9pZCI6MX0.Lt7xSkdVv20Z-zn9rR2VrNn5n9rFdtlWR_xuT3jmP2Q

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4MzIxOTM0LCJpYXQiOjE3MjgzMjE2MzQsImp0aSI6ImJhNjAwMDBiMTU3MzRkM2ZhMWZlN2VlNWY4ZDQ5NzE5IiwidXNlcl9pZCI6MX0.oytJ-fpp0gf4STT7qoGNBFHrGVHyexLYW2ZqGPL1gxU

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

### 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyODQwOTAzMSwiaWF0IjoxNzI4MzIyNjMxLCJqdGkiOiI3ZjdmZDExNDhjZTg0Njk5YTdiYmY2OWZlNmRiMzczYSIsInVzZXJfaWQiOjF9.KRzvCrbOC_XbxFqjGWf9iTf4lhlnWAdddfCjp7dPrFM"
}

###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjYxODgyLCJpYXQiOjE3MzM2NjE1ODIsImp0aSI6ImNiNDEwNzVhYzgyNjQ5NDA5NDNmMWM5ODFlNTBjMzc0IiwidXNlcl9pZCI6Mn0.VrzNai7WmnYC7nbaEM1CcqDIyhPIQIKNHSuAiRdDmvE

###
GET http://localhost:8000/orders/8f1e83a6-8f36-442e-8c1c-09dd1ae20484/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjYyMjE2LCJpYXQiOjE3MzM2NjE5MTYsImp0aSI6ImViOTFmODI4ZDFlMjRjMGI4Y2I0OTlhYmYyNDViMmYwIiwidXNlcl9pZCI6Mn0.ixKbx2Gocm3B-KDirqWlq1MVizCr6FGI-AJ3Ty4Roqo

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzNjc3NTQxLCJpYXQiOjE3MzM2NzcyNDEsImp0aSI6ImJhOGU1YWUwMmY3MTRmMGZiYzIxZjY5ZmFjZGI4NzM0IiwidXNlcl9pZCI6MX0.Jo9l2_G9D-pPp0rxoasCnVhr4Owpg12vEdSNGONRbyc

{
	"status": "Pending",
	"items": [
		{
				"product": 2,
				"quantity": 2
		},
		{
				"product": 3,
				"quantity": 1
		}
	]	
}